# Generated by Django 4.2.5 on 2023-11-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pet', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=20)),
                ('data', models.CharField(max_length=10)),
                ('observacao', models.TextField()),
            ],
        ),
    ]
